### ISSUE TITLE
Application Portal - News Update Content Editor

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#1]
Issue:  Within the content editor for news updates, the Heading and Paragraph buttons are misaligned. 

![image](https://cloud.githubusercontent.com/assets/5805454/3434756/c7666878-008d-11e4-8c10-4fb22118e1fd.png)

Resolution:  Please fix or remove this section.  Are they really necessary anyway?

**Comment by jday3** [comment]
I just removed the unneccesary buttons.

**Comment by JMurk** [comment]
Looks good.  Closing.
