### ISSUE TITLE
Admin - Utility Viewer - View Assignments Mismatch in Viewer

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#11]
Issue:  it appears that updating assigned views to a user within the Admin page does not have an impact when in the Utility Viewer.  In the viewer, all views have been accessible, regardless of the view(s) assigned.

**Comment by jday3** [comment]
This is on the app side. Assigning to Lu.

**Comment by JMurk** [comment]
Not hitting cityUsers until launch.  Will test then.

**Comment by JMurk** [comment]
Tested in dev.  Looks OK.
