### ISSUE TITLE
Admin - UV Trace Tool Permissions

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#12]
Issue: updating permissions in Admin for the trace tool do not affect the tool in UV.  After updating through all three permissions, the Select Mains button is still present.

Also, adding or removing users from the Trace tool do not impact the UV trace tool functionality

**Comment by jday3** [comment]
This is on the mobile app side. Assigning to Lu.

**Comment by JMurk** [comment]
Not hitting cityUsers until launch.  Will test then.

**Comment by JMurk** [comment]
Tested on Dev and it appears that the UV does not recognize the Valve permissions.

**Comment by JMurk** [comment]
Complete.
