### ISSUE TITLE
Admin - SSO Permissions

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#13]
Issue: updating permissions from Admin do not seem to impact the SSO tool.  The tool seems to consistently present the admin privilege level.  Primarily, the Delete button appears for all permission levels, and all SSO's are editable for all users (regardless of status).

**Comment by jday3** [comment]
This is on the mobile app side. Assigning to Lu.

**Comment by JMurk** [comment]
This is an issue with the SSO application.  Will log issue there.
