### ISSUE TITLE
Admin - Grid Display on iPad mini landscape view

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#14]
Issue: When the iPad mini is turned landscape, the user directory section expands too much, so that the View grid is difficult to see and navigate.  The user directory should be the primary element in this screen. 

This error persists for all grid views.

![untitled picture](https://cloud.githubusercontent.com/assets/4103847/3642905/d56a9c0e-10c9-11e4-9fa2-da3f763568bb.jpg)

**Comment by jday3** [comment]
The application wasn't designed for tablet use, but the user directory section was reduced in size anyway.

**Comment by JMurk** [comment]
Looks good now.  Confirmed complete.
