### ISSUE TITLE
Application Portal - Banner Collapse

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#15]
Issue:  when viewing the AP on desktop, the banner collapses upon the user scrolling down within the page.  This is not the case on mobile (iPad mini).  Is the banner designed to collapse across devices?  Functionality should probably be consistent across devices.

**Comment by leeensminger** [comment]
Also, it seems that the banner expands upon scroll up on desktop.  So the user experience is something like:
1. scroll down to bottom of page.  banner collapses.
2. scroll back up slightly.  banner expands again.

I'm not sure what the functionality is intended to be here, though this seems a little unclean.

**Comment by jday3** [comment]
This is by design (collapse on desptop, not on mobile). It can be changed if that's what we want to do.

**Comment by JMurk** [comment]
I think that it is OK as is.
