### ISSUE TITLE
Application Portal - News Editor on Mobile

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#16]
Issue:  The news content edit button (the pencil) does not work on the iPad mini.  Users therefore have no method of editing news content while on mobile.

The button does work on desktop.

**Comment by jday3** [comment]
Joe - is this something worth fixing or can we just assume whomever is editing the news will be doing it on a desktop?

**Comment by JMurk** [comment]
We should fix it at some point, but I have moved it to a low priority issue.  This wouldn't prevent us going live.

**Comment by JMurk** [comment]
I'm going to close this issues as unresolved.  Anyone editing should be doing so on desktop as Jesse said above.
