### ISSUE TITLE
Admin - FSE Permissions

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#17]
Issue:  Permission levels assigned in Admin do not have an impact in the FSE application.  Inspector privileges should not be able to edit FSE ID, and should not be able to view Delete button.  Both functionalities are currently present for Inspectors.

**Comment by jday3** [comment]
This is on the mobile app side. Assigning to Lu.

**Comment by JMurk** [comment]
FSE app does not hit cityUsers DB.  This is a non issue for the admin portal.

**Comment by JMurk** [comment]
Correction:  It does, however the app responds appropriately.  Non-issue.
