### ISSUE TITLE
Admin - View Grid Record Count is not Correct

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#18]
Issue: the record count for the Views grid tables does not display correctly in the bottom right.  It appears, though I have not counted to be certain, that the counter is counting the total users within all views, and is not updating when displaying the single-View grid.

![untitled picture](https://cloud.githubusercontent.com/assets/4103847/3643123/fb17d332-10cd-11e4-9a12-d78ea8b4bbe3.png)

**Comment by jday3** [comment]
This should be correct now.

**Comment by JMurk** [comment]
Confirmed complete.
