### ISSUE TITLE
Admin - Adding User from User Directory to a Specific View

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#19]
Issue: when in a single View grid display, adding a user via User Directory does not actually add the user to the view.  

Steps to recreate:
1. Open specific View
2. search the User directory for a user not on the list
3. Add the user.  No functionality is triggered.

**Comment by jday3** [comment]
Done.

**Comment by JMurk** [comment]
Confirmed complete.
