### ISSUE TITLE
Application Portal - Add User Guides

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#2]
Please add links to the "Help Documentation & User Guides" section.

Joe to provide web pdfs to Jesse via email.

**Comment by jday3** [comment]
Do we still want to do this before going live?

**Comment by JMurk** [comment]
Yes, we should at least have Utility Viewer User guides linked if possible.

**Comment by jday3** [comment]
Okay, can you send them to me?

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
