### ISSUE TITLE
Add Link To Portal Page

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#20]
Within any application accessible from the Application Portal, include a link back to the portal for easier navigation.

**Comment by jday3** [comment]
Done. Clicking on banner links to portal

**Comment by JMurk** [comment]
What about for other apps? (FSE, SSO, UV Mobile, Leaks).  I guess that would be on Lu's side?

**Comment by jday3** [comment]
Yeah, that's right. Assigning to Lu.

**Comment by JMurk** [comment]
Lu- Please add a method to link back to the portal page from all mobile applications and the standard utility viewer.  This is lower priority.

**Comment by JMurk** [comment]
Home button added to all mobile applications.
