### ISSUE TITLE
Admin - UV Grid User Search

### ISSUE THREAD

**Issue by leeensminger** [JMurk/Application_Portal_Admin#21]
Enhancement: Within the View grid tables, it is sometimes easy to miss a user (record) you are looking for.  Including a type-ahead search box for each grid, which would filter the grid display by any field matching the search characters, would enable users to quickly find a user within a grid.

Optionally, color shading every other row within the grid would assist users in locating specific records as well.

**Comment by jday3** [comment]
Added filter textboxes for each of the grids and added shading for alternate rows.

**Comment by JMurk** [comment]
Confirmed complete.
