### ISSUE TITLE
Admin - When Adding New Users, Full Name is not populated

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#24]
Issue:  When adding new users, the database is not populating full name.  At least not for users that already exist in the database being added to new apps.

![image](https://cloud.githubusercontent.com/assets/5805454/4208064/c5c2fee4-385c-11e4-9b20-40ec7cc73275.png)

**Comment by kanglu666** [comment]
I just checked the code for both admin portal UI and web services, 
it's not a simple fix for this, there are also some other related  things need to be updates.
i think it's better  assign admin portal issues or updates to Jessey.

**Comment by JMurk** [comment]
When a brand new user is added, the system needs to populate the following fields:

-Full_name
-Email
-Title

**Comment by jday3** [comment]
This is resolved locally and I will push to prod tomorrow morning

**Comment by jday3** [comment]
This is now on dpwview

**Comment by JMurk** [comment]
Please push to dev as well, if possible.

**Comment by jday3** [comment]
It's on dev now

**Comment by JMurk** [comment]
Confirmed complete.
