### ISSUE TITLE
Admin - AD Search - Not Returning Users with No Email

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#25]
**Issue**: Users without a city email (login only) are not being returned in the search box.

Example case:  Carlo.Olivi

**Resolution**: Please investigate and resolve accordingly.

**Comment by kanglu666** [comment]
updated at dev, please test

**Comment by JMurk** [comment]
Confirmed, please push to prod.

**Comment by JMurk** [comment]
What did you do to resolve this issue?

**Comment by kanglu666** [comment]
Jessey fixed this.

**Comment by JMurk** [comment]
Confirmed complete.
