### ISSUE TITLE
Admin - Add Columns

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#27]
For Mobile Applications, please add Columns for:

-Full Name
-Title
-Email

Place the columns in between Username and Role in the order above.

These should be editable.  Also, is it possible to enforce required fields here?  If so, they should all be required.

**Comment by jday3** [comment]
This is resolved locally and I will push to prod tomorrow morning

**Comment by jday3** [comment]
This is now pushed to dpwview. When you add a user, full name, title and email are brought over and editable. If you click on a field, edit, and then press enter, it will be saved to the server.

**Comment by JMurk** [comment]
Looks good on prod.  Is it possible to put on dev as well?

**Comment by jday3** [comment]
It's on dev now

**Comment by JMurk** [comment]
Confirmed complete.
