### ISSUE TITLE
Portal - Add OAM Activity Manager

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#28]
Add an icon for the OM Activity Manager under Desktop Applications.  If possible, this should be completely hidden for users that do not have access.  Much like the Admin tool.

**Comment by jday3** [comment]
We need some content for this (icon/description). Also @kanglu666, what is the url?

**Comment by JMurk** [comment]
E-mail sent to Tiffany for an icon.  I will forward when I receive it.  Dev URL is http://dpwdev.baltimorecity.gov/water/activitymanager/index.aspx

**Comment by jday3** [comment]
You can now access the oam app (dev) from the production portal. I will update the icon, url, etc. when they come available. I will push everything to dev as soon as I'm able to connect to the dev sql instance.

**Comment by JMurk** [comment]
Can you link the OAM prod version in prod portal please?  URL is http://dpwview.baltimorecity.gov/water/activitymanager/index.aspx

Should have an icon tomorrow sometime.

Description can be:

"Perform various asset management activities including SSO investigation, lateral CCTV review, repair and rehab recommendation, and preventive maintenance flagging."

**Comment by jday3** [comment]
Done. When you get the icon let me know and I'll throw it up there.

**Comment by JMurk** [comment]
Confirmed complete.
