### ISSUE TITLE
Portal Page - Add User Guide for PST

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#32]
When Regina has a completed User Guide available for the PST application, please add it to the Help Documentation section.

**Comment by JMurk** [comment]
You can find the PDF here:  M:\2010\13101078\Reports\Geospatial\Environmental Compliance\User Guide (v1.2).

Also, please add the Water Valve Status App User Guide:
M:\2010\13101078\Reports\Geospatial\Valve Status Mobile\User Guide (v1.1)

**Comment by jday3** [comment]
Done on dev/prod (water valve status is not shown in prod)

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
this is done

**Comment by JMurk** [comment]
Confirmed complete.
