### ISSUE TITLE
Portal Page - Meter Locations Report

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#33]
I have received more detail on the "Meter Locations" report.  Per Amy:

"It is balt-sql-fc and the database is DPW_waterbilling.  See if that works and I had used the query below previously to create an extract of the needed data.

 SELECT dbo_mbr_account_info.service_address, dbo_mbr_account_info.service_zip,      dbo_mbr_account_info.serv_sz, dbo_mbr_account_info.meter_sz, dbo_mbr_account_info.fst_half_meter_location, dbo_mbr_account_info.second_half_meter_location INTO METER_LOC_DETAILS
FROM dbo_mbr_account_info;

I think we may already have some connection info for this, but I'm not sure.  Let me know if we need a user name and password.

**Comment by JMurk** [comment]
U:  DPW_WaterMainBreaks
P:   Y%6vRIux8D

**Comment by jday3** [comment]
Note: balt-sql-fc should be referenced as 169.156.54.17

**Comment by jday3** [comment]
Done on dev

**Comment by JMurk** [comment]
Can you add a description that says "Detailed descriptions of water meter locations for all addresses in the City"

**Comment by jday3** [comment]
sure, done

**Comment by JMurk** [comment]
Confirmed complete

**Comment by JMurk** [comment]
Sorry, one little thing.... can you add a period at the end of the description?

**Comment by jday3** [comment]
Done
