### ISSUE TITLE
Portal Page - Reports - Daily Location Sheets Error

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#34]
**Issue:** When trying to download the Daily Location Sheet report, I get the following error:

![image](https://cloud.githubusercontent.com/assets/5805454/7459982/d55ef120-f26d-11e4-9325-50d012bdfdc3.png)

**Resolution:**  Please investigate and resolve accordingly.

**Comment by jday3** [comment]
I need to know the source of the daya. In the word document you sent me a while ago, you mentioned that you need to create a view

**Comment by JMurk** [comment]
Sorry, it's called V_LOCATION_SHEET

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
