### ISSUE TITLE
Portal Page - Reports - Naming Convention

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#35]
Can you update the naming convention to all reports from the portal to be:

_reportname _date_time_

**Example:**
CustomerList_05042014_1000AM.xlsx

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Can you do the same for water main breaks, dpw street cuts, and daily location sheets?

**Comment by jday3** [comment]
Yup it should be updated now

**Comment by JMurk** [comment]
Confirmed complete.
