### ISSUE TITLE
Portal Page - Customer List Report - Stopped Running?

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#36]
**Issue:**  The naming convention of the Customer List report exported from the portal page suggests that a new report has not been generated since 5/1 (in dev).

![image](https://cloud.githubusercontent.com/assets/5805454/8161520/948e3004-1345-11e5-8be6-d82a1e7a46d7.png)

**Resolution:**  Please investigate and resolve accordingly.

**Comment by jday3** [comment]
Service was stopped, not sure why but it is running now.

**Comment by JMurk** [comment]
Confirmed complete.
