### ISSUE TITLE
Portal Page - Reports - Backlog Reports - Descriptions

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#37]
Please add the following as descriptions for the work order and service request backlog reports:

Work Order:  "Summary of current Work Orders in Cityworks"
Service Requests "Summary of current Service Requests in Cityworks"

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.  Please push these reports up to production.

**Comment by jday3** [comment]
done, service started as well

**Comment by JMurk** [comment]
Confirmed complete.
