### ISSUE TITLE
Admin Tool - Adding Users - Adds the Wrong User/Additional User

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#38]
**Issue:**  When adding a new user from the User Directory, the system will occasionally add the wrong user (i.e. another one on the list after a search) or add the user above the one selected in addition.

**Resolution:** Please investigate and resolve accordingly.

**Comment by JMurk** [comment]
It seems to be adding the first user in the search results along with the selected user.  Only seems to happen when the selected user is not first on the list.

**Comment by jday3** [comment]
Fixed on dev.

**Comment by JMurk** [comment]
Confirmed complete, please push to prod

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
