### ISSUE TITLE
Portal Page - Redesign Icon Layout 

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#39]
Please redesign the layout of the application portal to be a "responsive grid."  The Icon should be on the right of the container, with it's description to the left.  There no longer needs to be a distinction between Mobile and Desktop, however the names of the app should include "Mobile" at the end if they are mobile.

I think Utility Viewer should be labeled:  "Utility Viewer (Desktop)"

**Comment by jday3** [comment]
done on dev

**Comment by JMurk** [comment]
Please change the Activity Manager description to read:

"Web tool to view, capture, and analyze data for specific programs and workflows."

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.  Ready for prod.

**Comment by JMurk** [comment]
Complete on Prod
