### ISSUE TITLE
Admin - Update Banner

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#4]
Please update the page banner to match the portal page.  This will require an updated banner image from Tiffany.  

![image](https://cloud.githubusercontent.com/assets/5805454/3447386/c801fb7a-014c-11e4-9031-853fb5d90199.png)

**Comment by JMurk** [comment]
Use file here:  M:\2010\13101078\Reports\Geospatial\Portal Page\Design\Admin_Header.jpg

**Comment by jday3** [comment]
Done

**Comment by JMurk** [comment]
Confirmed complete.
