### ISSUE TITLE
Portal Page - Add Surface Repair Report

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#40]
Please add the Surface Repair report to the reports section of the portal.  I will provide the details of the report in an email.

**Comment by JMurk** [comment]
The surface repair report can be a select \* from V_ALL_OPEN_SURFACE_REPAIRS.  The description in the portal can read "All open surface repair Work Orders."

**Comment by jday3** [comment]
This view needs to be added to balt-sql-dev.DPW_CityworksReporting

**Comment by JMurk** [comment]
The view has been added to the database.

**Comment by jday3** [comment]
Now on dev

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
If it is not too important to have this week, I will wait until the cityworks migration since it will require reworking the code to point to oracle instead of sql server. Your call

**Comment by JMurk** [comment]
That should be fine.  If it becomes more of a priority, I will let you know.

**Comment by JMurk** [comment]
Per Amy we now need this pushed to prod using the Oracle instance.

**Comment by jday3** [comment]
This is done

**Comment by JMurk** [comment]
Confirmed complete.
