### ISSUE TITLE
Portal Reports - Prepare for Cityworks Migration

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#41]
To prepare for our Cityworks Migration to the local environment, we need to re-map all portal reports to the reporting database at the City.  Here is the connection information:

Server: BALT-SQL-DEV
DB: DPW_CityworksReporting
UN: azteca
PW: azteca

Please remap the reports in Dev to this database.  Once we migrate, we will need to push this to the production portal and map to the production reporting database.

**Comment by jday3** [comment]
Okay, this is completed. The reports on dev are no longer coming reading from the current production cityworks oracle db. A couple of things to note: 
1. The views for the Work Order and Service Request backlog reports were not migrated into the dev sql database. I migrated them over, but we should be sure that they will be moved into the production database.
2. The 'Meter Locations' report is getting its data from the Water Billing database, so this will most likely need to be updated when the water billing migration takes place.

**Comment by JMurk** [comment]
Sounds good.  We will likely copy the current reporting database up to production (remapping all the synonyms), so the views should stick.  

I will leave this open for when we go live,  the production reports will need to be remapped.

**Comment by jday3** [comment]
Considered complete
