### ISSUE TITLE
Portal Reports - Work Order Backlog - Missing Hydrant Out of Service

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#42]
According to Amy, the Work order Backlog report is missing HYDRANT OUT OF SERVICE Work Orders.  Upon check, it appears that is indeed the case.  

![image](https://cloud.githubusercontent.com/assets/5805454/9391798/f0d882a8-4746-11e5-863a-9e5004aa3be8.png)

Please investigate and resolve accordingly.

**Comment by jday3** [comment]
This is resolved in dev. The WO_GP.DESCRIPTION column needed to be updated to all uppercase values.

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.

**Comment by jday3** [comment]
this is done

**Comment by JMurk** [comment]
Confirmed complete.
