### ISSUE TITLE
Reports - Automatically Email Reports

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#44]
Please create a email service that sends the current production "DPW Street Cuts" and "Surface Repairs" report to streetcuts@baltimorecity.gov and cc amy.purves@baltimorecity.gov, bpatel@baltimorecity.gov, joe.murk@baltimorecity.gov

These reports should be sent at 8 AM every morning.

**Comment by jday3** [comment]
this is done

**Comment by JMurk** [comment]
Confirmed complete
