### ISSUE TITLE
Reports - Surface Repair Link Broken

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#45]
The link to the Surface Repair Work Order report in the daily email is broken.  See:

http://dpwview.baltimorecity.gov/water/portal/Reports/SurfaceRepair/SurfaceRepair10272015_0700AM.xlsx

**Comment by jday3** [comment]
Surface Repair reports were being cleaned up too frequently (deleting all over a day old). This was increased to 15 days.

**Comment by JMurk** [comment]
Link is still broken this morning...

http://dpwview.baltimorecity.gov/water/portal/Reports/SurfaceRepair/SurfaceRepair10292015_0700AM.xlsx

**Comment by jday3** [comment]
Fixed now

**Comment by JMurk** [comment]
Confirmed complete.
