### ISSUE TITLE
Reports - Date Formatting

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#46]
Due to the switch from Oracle to SQL Server, the dates in exported spreadsheets have become improperly formed.  Please update all spreadsheets.

![image](https://cloud.githubusercontent.com/assets/5805454/10759167/27d66142-7c8c-11e5-86e8-78d6ce265f3f.png)

**Comment by jday3** [comment]
Should be fixed now.

**Comment by JMurk** [comment]
Confirmed complete.
