### ISSUE TITLE
Application Portal - Add Cityworks Links

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#48]
Can you please add a link to Cityworks to the application portal?  All users will have access.

Description:  The Cityworks application is used for tracking maintenance activities for DPW.  This application can be used in Office or Field mode.

Icon:  http://apk-dl.com/detail/image/com.cityworks.android2014-w250.png

Link:  https://dpwapps.baltimorecity.gov/cityworks/Default.aspx

I will provide the dev link when the site is configured.

**Comment by jday3** [comment]
done, added to dev also (/cityworkstest instead of /cityworks)

**Comment by JMurk** [comment]
The dev icon link seems to be broken, otherwise looks good.

![image](https://cloud.githubusercontent.com/assets/5805454/11157014/1c923bd2-8a1d-11e5-9064-c0ad5bad4f6c.png)

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Confirmed complete.
