### ISSUE TITLE
Admin - UV Add Users

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#5]
Issue:  Add users not working for Utility Viewer Views.  Upon clicking the + button, nothing happens.  

The function works with all other apps/permissions.

**Comment by jday3** [comment]
Users are being added to the bottom of the grid without automatically scrolling to the row. Will change in code and then update.

**Comment by jday3** [comment]
Done.

**Comment by JMurk** [comment]
Confirmed complete.
