### ISSUE TITLE
Portal - User Guides - Remove Advanced Column

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#50]
Please remove the Advanced column for User Guides.  The Advanced Utility Viewer Guide can be listed on a separate line as “Utility Viewer – Main Shutdown and Valve Status."

Also, please rename the "Basic User Guide" Column header to "Download User Guide"

![image](https://cloud.githubusercontent.com/assets/5805454/11148134/ce311596-89e8-11e5-80dc-343446af5c7e.png)

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Please add the line for “Utility Viewer – Main Shutdown and Valve Status." with the advanced user guide as the downloadable link.

Implement in dev as well.

**Comment by jday3** [comment]
done on dev/prod

**Comment by JMurk** [comment]
Confirmed complete.
