### ISSUE TITLE
Portal - Update Application Descriptions

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#51]
Please update the following application descriptions:

-Utility Viewer (Desktop) – View all DPW utilities, service requests, work orders, operational data, project information, and utility status.
-Utility Viewer (Mobile) – View all DPW utilities and activities on a tablet device.
-Cityworks Activity Browser – Search for Cityworks Service Requests and Work Orders.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Please make these changes in dev as well.  Also, "Utilities" in should be lowercase in the Utility viewer descriptions.

**Comment by jday3** [comment]
done

**Comment by JMurk** [comment]
Utilities is still capitalized in dev and prod

![image](https://cloud.githubusercontent.com/assets/5805454/11698160/62a7a684-9e8b-11e5-8dad-f47a568cc878.png)

**Comment by taojun545** [comment]
Updated the description on dev.

**Comment by JMurk** [comment]
Appears to have been pushed to prod as well.  Confirmed complete.
