### ISSUE TITLE
Portal - Surface Repair - Add Columns

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#52]
**Update Description:** The current surface repair report that is available on the application portal page and also automatically emailed needs to be updated to include additional columns.  

![image](https://cloud.githubusercontent.com/assets/5805454/13471911/a504ec1c-e080-11e5-8363-9710772a0c4b.png)

The additional columns are:

*IS EXCAVATION NEEDED?
*ITIC SUBMITTED/MISS U CALLED
*MISS UTILITY #
*DATE OF CUT
*EXCAVATION SIZE (W X L X D)
*SHORING TYPE
*PLATES RAMPED AND SPIKED?
*TEMP PATCH DATE
*TEMP PATCH SIZE (W X L)
*COMPACTED?
*STENCILLED?
*HAS SERVICE BEEN RESTORED?

I have the code to update the underlying database view, but am waiting until the updates can be implemented on the front-end in order to avoid breaking the report.  Please coordinate with me at the time of development.

**Comment by taojun545** [comment]
Updated both on dev and prod.
