### ISSUE TITLE
Application Portal - Log Out

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#6]
Please add a Log Out button and function to the admin portal.  Upon log out, the user should be redirected to a page where they can access the portal again.

**Comment by BC89** [comment]
This may be problematic since we are authenticating against AD and not forms based. Why do we need it. What is the use case that domain-based rules don’t cover?

**Comment by JMurk** [comment]
Multiple valve crew members use the same machines that are off of the city domain (they do not have to log in separately to the computer.)  If all users want to use the application, they need to clear their cache to log out before another user can log in.

**Comment by jday3** [comment]
This should only be an issue if somebody leaves the browser open and someone else uses it soon after. The authentication is automatically cleared by closing the browser, and I think also times out at a certain point of inactivity.

**Comment by JMurk** [comment]
Closing for now, potential future enhancement if requested.
