### ISSUE TITLE
Application Portal - Request Access Instructions

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#7]
When a user clicks "Request Access" the system should mailto: utilityviewer@baltimorecity.gov and provide a message with the following instructions:

"In your e-mail request, please include a detailed description of the permission level you are requesting and why you are requesting it.  Be sure to CC your supervisor for their approval."

**Comment by jday3** [comment]
Is this for all applications or just Utility Viewer Desktop/Mobile?

**Comment by JMurk** [comment]
All applications.

**Comment by jday3** [comment]
Done.

**Comment by JMurk** [comment]
Confirmed complete.
