### ISSUE TITLE
ALL APPLICATIONS - Redirect .HTML to .ASPX

### ISSUE THREAD

**Issue by JMurk** [JMurk/Application_Portal_Admin#9]
Prior to changing all application URLs from .html to .aspx, please be sure that the old .html pages will redirect to the new .aspx pages.

**Comment by kanglu666** [comment]
.html page will be redirect to .aspx page for SSO app. please test

i will make all other changes once new data in place.

**Comment by JMurk** [comment]
Confirmed for SSO.  Assigning back to Lu for other apps.

**Comment by JMurk** [comment]
Will test once pushed.  All should be in place.

**Comment by JMurk** [comment]
Completed.
